deployments:
  paperless:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: "3.2.0"
    ports:
      - name: http
        containerPort: 8000
    volumeMounts:
      - { name: data, mountPath: /usr/src/paperless/data }
      - { name: media, mountPath: /usr/src/paperless/media }
      - { name: export, mountPath: /usr/src/paperless/export }
      - { name: consume, mountPath: /usr/src/paperless/consume }
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: paperless-data
      - name: media
        persistentVolumeClaim:
          claimName: paperless-media
      - name: export
        persistentVolumeClaim:
          claimName: paperless-export
      - name: consume
        persistentVolumeClaim:
          claimName: paperless-consume
    env: 
      - name: PAPERLESS_REDIS
        value: "redis://valkey:6379"
      - name: PAPERLESS_DBENGINE
        value: "sqlite"
      - name: PAPERLESS_URL
        value: "https://paperless.ibenyahia.fr"
      - name: PAPERLESS_CSRF_TRUSTED_ORIGINS
        value: "https://paperless.ibenyahia.fr"
      - name: PAPERLESS_APPS  
        value: "allauth.socialaccount.providers.openid_connect"
    envFrom:
    - secretRef:
        name: paperless-secret
    enableServiceLinks: false
  valkey:
    image:
      repository: valkey/valkey
      tag: "9-alpine"
    ports:
      - containerPort: 6379
    volumeMounts:
      - { name: valkey-data, mountPath: /data }
    readinessProbe:
      exec:
        command: ["valkey-cli", "ping"]
      initialDelaySeconds: 2
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ["valkey-cli", "ping"]
      initialDelaySeconds: 5
      periodSeconds: 10
    volumes:
      - name: valkey-data
        emptyDir: {}

externalSecrets:
  paperless-secret:
    data:
      - secretKey: PAPERLESS_SECRET_KEY
        remoteRef:
          key: paperless-secret-key

services:
  valkey:
    enabled: true
    ports:
      - port: 6379
        targetPort: 6379

  paperless:
    enabled: true
    ports:
      - port: 8000
        targetPort: 8000
    expose:
    - lan
    - public


persistentVolumeClaims:
  paperless-data:
    enabled: true 
    size: 10Gi
  paperless-media:
    enabled: true
    size: 50Gi
  paperless-export:
    enabled: true
    size: 10Gi
  paperless-consume:
    enabled: true
    size: 10Gi