apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: generic-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/iliesbenyahia/homeops.git
      revision: HEAD
      directories:
      - path: apps/generic-apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      sources:
      - repoURL: https://github.com/iliesbenyahia/homeops.git
        ref: 'values'
        targetRevision: HEAD
      - repoURL: https://github.com/iliesbenyahia/homeops.git
        targetRevision: HEAD
        path: 'charts/generic-app'
        helm:
          valueFiles:
            - '$values/apps/generic-apps/{{.path.basename}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
